### ISSUE TITLE
Karma + Karma-bro + proxyquireify don't get along

### ISSUE THREAD

**Issue by xcambar** [thlorenz/proxyquireify#15]
Hi,
I've been struggling for a day with trying to have proxyquireify in Karma with Karma-bro.

In a few words: Proxyquireify adds the authentic `require` calls so Browserify bundles them, but it seems that the prelude is not changed so the mocked modules are not loaded.

Here's a example repo: https://github.com/xcambar/karma-bro-proxyquireify

Did I do something wrong? What do you think?

/cc @Nikku because I feel like Karma-bro might be involved in this situation.

**Comment by bendrucker** [comment]
This is the same as #21 and there's a long discussion there. Turned out it was a one line fix, merging in #22.

**Comment by K4LiN** [comment]
I've got exactly the same issue with the current versions of proxyquire:
    "proxyquire-universal": "^1.0.8",
    "proxyquireify": "^3.2.1",

I checked the @xcambar git repo and applying patch or updating the proxyquirefy to current isn't solving the issue.

Ps. sorry for digging up the thread ;)

**Comment by bendrucker** [comment]
Because this issue is pretty ancient, I have to ask that you open a new one if you think you've found a legitimate bug. This is in large part in fairness to the original contributors to the discussion who shouldn't be forced to unsubscribe from notifications on a 3 year old thread.

It's possible a major version of browserify or karma* broke something. To start we'll need a project (public repo) that we can clone, run `npm install && npm test`, and get `exit 1` with a trace of the error you're seeing. As few deps as possible, e.g. use `assert` and not something like `mocha`.
