### ISSUE TITLE
Rewrite require('proxyquire') calls

### ISSUE THREAD

**Issue by bendrucker** [thlorenz/proxyquireify#20]
I wrote [proxyquire-universal](https://github.com/bendrucker/proxyquire-universal) to allow you to use proxyquire in your tests and then turn it proxyquireify via a browserify plugin. From Thorsten via email:

> BTW: this (https://github.com/bendrucker/proxyquire-universal/blob/master/src/transform.js#L12) is pretty brittle as it would match inside messages, etc. as well.
Also it’d miss `require(“proxyquire”)` (double quotes).

> Seems like it’d be better integrated with proxyquireify to avoid overhead and order dependance of an extra transform, but lets keep discussing there.

Wrote it up quickly to solve @beckyconning's issue in https://github.com/Nikku/karma-bro/issues/40 so it's definitely a little brittle.

I haven't done a lot of work with syntax parsers — any recs on what to use there?

**Comment by bendrucker** [comment]
Wanted to loop back on this. I'm all for reusing code from exposify, but wouldn't it make more sense to extract that functionality into a separate module and have both depend on it?

**Comment by beckyconning** [comment]
:+1:

**Comment by thlorenz** [comment]
Yeah, I'm still not sure if this belongs anywhere in the packages you mentioned.

- exposify definitely has nothing to do with either proxyquire and should not need to know anything about them
- proxyquireify could know about proxyquire, but I think it's problematic

I think the best idea is actually to have a unifying package that knows about both and adapts the code to automatically use the right one depending on the situation.
proxyquire-universal could be that package.
We could add links to it on the readme of both proxyquire and proxyquireify to make it easily discoverable.

> wouldn't it make more sense to extract that functionality into a separate module and have both depend on it?

if we go the route I suggested, only proxyquire-universal would have to depend on it

> instead of having something additional for users to think about.

Not much for the user to think about since there are 3 simple cases:

- a) your tests only run server side -> use proxyquire
- b) your tests only run client side -> use proxyquireify
- c) your tests run server side and client side -> use proxyquire-universal

**Comment by bendrucker** [comment]
I'm with you. In that case, the only remaining todos are documentation updates both here and on proxyquire, correct? I'll extract the require replacement transform into its own package when I have a chance but that's an internal implementation detail for now. Will send PRs for both proxyquire* repos if we're on the same page.

**Comment by thlorenz** [comment]
Thanks, sounds good.
Possibly you should also add the three cases I outlined to the proxyquire-universal page so users have it easy to decide when to use either proxyquire solution.

**Comment by bendrucker** [comment]
Cool. README commits on all three it is. Will send PRs this evening.

**Comment by thlorenz** [comment]
Sounds good, one thing I'd suggest is directly depend on proxyquire and proxyquireify. 

The reason is that you'd expect the user to run tests on client and server and thus they need both modules anyways.

The only reason not to do so that I can think of is to allow users to pick the version for each proxyquire.

**Comment by bendrucker** [comment]
Yeah that makes sense. I don't see any reason to allow people to pick their versions versus just matching major versions on both and then keeping up to date in the rare cases of major bumps.

**Comment by thlorenz** [comment]
Added you as collab here as well, so just update the README and let me review the PR then push to master. I'll republish.
Adding you to proxyquire as well so we can successfully manage the proxyquire* repos together and make them easy to use.

One other thing that'd be nice is if proxyquire-universal would document some API differences that do exist. For example proxyquireify cannot do any global overrides like proxyquire.
