### ISSUE TITLE
proxyquireify path problem with karma?

### ISSUE THREAD

**Issue by MadMub** [thlorenz/proxyquireify#60]
Currently using browserify with a rails project. the `rails-browserify` gem automatically sets up browserify to be able to import from `./assets/javascripts`, which allows us to import `./assets/javascripts/our_modules` like so: 

`var module = require('our_modules/foo')`

I am attempting to write tests, current setup uses karma, setting the following config allowed my unit tests to not break with those import paths.
```
browserify: {
  debug: true,
  paths: ['./../../app/assets/javascripts']
},
```
The nasty relative path is because the config file is located in a few nested folders. All tests and modules work. I'm now looking to integrate proxyquirefy in my tests for some stubbing. Here is my karma config:
```
browserify: {
   debug: true,
   plugin: [ 'proxyquireify/plugin' ],
   paths: ['./../../app/assets/javascripts']
 },
```
in bar.spec.js
```
var proxyquire = require('proxyquireify')(require);

var fooStub = {
  "our_modules/foo": function() {
    console.log('oy');
  }
}
var bar = proxyquire('our_modules/bar', fooStub)
```
I get the following error
```
Error: Cannot find module 'our_modules/bar'
  at /tmp/88bbd059aa3851dc6ea5da8a660f56f8.browserify:54:0 <- /User/madmub/project/node_modules/proxyquireify/lib/prelude.js:54:0
```
All I can infer is that proxyrequire cannot import the module (obviously), browserify was working with the path flag set, any idea why proxyrequireify would not pickup on that? I have had no luck looking online for similar bugs. Any help is appreciated sorry for long write up, thank you for all your time and hard work!

EDIT: looks like this issue has the solve
http://stackoverflow.com/questions/34531677/require-and-import-finds-module-but-proxyquireify-does-not

Not sure if the docs are clear/is this the intended behaviour? But in my test file I need to require the module, then proxy? Just glad its working, please feel free to close if it was a misuse and not an issue

**Comment by bendrucker** [comment]
Proxyquireify does inject `require` statements. Not sure what the SO answer based that suggestion on. 

https://github.com/thlorenz/proxyquireify/blob/6e2ae4466ac617662cfa0bdd3d9ee3d3cdcbc03b/lib/transform.js#L11-L12

I tried and failed to reproduce your issue without Karma:

https://github.com/bendrucker/proxyquireify-issue-60

As a maintainer of both projects, I'm highly inclined to blame karma-browserify here. In order to work around Karma limitations it's extremely complex and pretty brittle.

My guess here is that the transform isn't running on your file for some reason and that's causing the require statements to not be injected. If I have some spare time I'll try to fix it, but can't promise anything.

**Comment by MadMub** [comment]
It's worth mentioning we are stuck on an older version of browserify as a result of being on an older version of rails.
```
"browserify": "~10.2.4"
```
Which was released June 2015, not sure if that lends anything to the cause. Thank you for the quick reply and for even looking into it.

**Comment by bendrucker** [comment]
Definitely worth trying v13 then
